### PR TITLE
v3.2.0-1

### PR DESCRIPTION
**Pull request by romuloalves**
Upgrade sodium-native to **v3.2.0**.

### CODE REVIEW

**Comment by staltz** [comment]
@romuloalves Thanks for this! First I'll make a release candidate version of https://github.com/staltz/sodium-chloride-native-nodejs-mobile/ that uses 3.2.1, and run on android and ios, if it passes then I'll merge your PR.

**Comment by staltz** [comment]
It worked!

**Comment by staltz** [comment]
I released sodium-native-nodejs-mobile 3.2.0-1 and sodium-chloride-native-nodejs-mobile 1.5.0

**Comment by mixmix** [comment]
hooray. It's so sweet to have an ecosystem big enough to have parallel projects which incrementally improve one another

**Pull request merged**
